### ISSUE TITLE
We need to enable remote push notifications.

### ISSUE THREAD

**Issue by TheQuantumFractal** [SpartanConnect/restful-api-backend#17]
Remote push notifications must come from a server because of winter and summer break etc.

**Comment by encadyma** [comment]
@TheQuantumFractal Push notifications do not necessarily have to come from this backend. Instead, the app can use a service such as OneSignal that can provide the resources to manage remote push notifications.

**Comment by nrlysek** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [We need to enable remote push notifications.](https://trello.com/c/kn1qVtpu/3-we-need-to-enable-remote-push-notifications)

**Comment by nrlysek** [comment]
We are currently working on this. Updates will come in #21.
Duplicate: Closing Issue.
